    Resources:
      AWSSERVICEROLEFORECS:
        Type: 'AWS::IAM::ServiceLinkedRole'
        Properties:
          AWSServiceName: es.amazonaws.com
          Description: 'Role for ES to access resources in my VPC'
          
       