    AWSTemplateFormatVersion: '2010-09-09'
    Description: ElasticsearchDomain resource
    Metadata:
      AWS::CloudFormation::Interface:
        ParameterGroups:
        - Label:
            default: "ElasticSearch Configuration"
          Parameters:
            - DomainName
            - EBSEnabled
            - EBSVolumeSize
            - ElasticsearchVersion
            - InstanceCount
            - InstanceType
            - DedicatedMasterType
            - DedicatedMasterCount
        - Label:
            default: "CIDR Block"
          Parameters:
            - VpcCidr
            - SubnetCidr1
            - SubnetCidr2
        - Label:
            default: "AvailabilityZone for Subnets"
          Parameters:
            - AvailabilityZone1
            - AvailabilityZone2
        - Label:
            default: "Environment Name"
          Parameters:
            - Environment
            - Platform
    Parameters:
      Environment:
        Description: QA
        Type: String
        Default: TBD
        MinLength: '1'
        MaxLength: '25'
      Platform:
        Description: Widget
        Type: String
        Default: TBD
        MinLength: '1'
        MaxLength: '25'
      DomainName:
        Description: User defined Elasticsearch Domain name
        Type: String
      EBSEnabled:
        Description: Specifies whether Amazon EBS volumes are attached to data nodes in the Amazon ES domain
        Type: String
        AllowedValues: [true, false]
        Default: true
      EBSVolumeSize:
        Description: 'The size of the EBS volume for each data node'
        Type: Number
        Default: 10
      ElasticsearchVersion:
        Description: 'Elasticsearch version'
        Type: String
        Default: '7.10'
        AllowedValues: ['7.10','7.9', '7.8', '7.7', '7.4', '7.1', '6.8', '6.7', '6.5', '6.4', '6.3', '6.2', '6.0', '5.6', '5.5']
      InstanceCount:
        Description: No of data nodes.
        Type: 'String'
        Default: 2
        AllowedValues: ['2','3','4']
      InstanceType:
        Description: 'The instance type for your data nodes.'
        Type: 'String'
        Default: 't2.small.elasticsearch'
        AllowedValues:
         - c4.large.elasticsearch
         - c4.xlarge.elasticsearch
         - c4.2xlarge.elasticsearch
         - c4.4xlarge.elasticsearch
         - c4.8xlarge.elasticsearch
         - i2.xlarge.elasticsearch
         - i2.2xlarge.elasticsearch
         - i3.large.elasticsearch
         - i3.xlarge.elasticsearch
         - i3.2xlarge.elasticsearch
         - i3.4xlarge.elasticsearch
         - i3.8xlarge.elasticsearch
         - i3.16xlarge.elasticsearch
         - m4.large.elasticsearch
         - m4.xlarge.elasticsearch
         - m4.2xlarge.elasticsearch
         - m4.4xlarge.elasticsearch
         - m4.8xlarge.elasticsearch
         - r3.large.elasticsearch
         - r3.xlarge.elasticsearch
         - r3.2xlarge.elasticsearch
         - r3.4xlarge.elasticsearch
         - r3.8xlarge.elasticsearch
         - t2.small.elasticsearch
         - t2.medium.elasticsearch
         - t3.small.elasticsearch
         - t3.medium.elasticsearch
      DedicatedMasterType:
        Description: 'The instance type for your data nodes.'
        Type: 'String'
        Default: 't2.small.elasticsearch'
        AllowedValues: 
         - c4.large.elasticsearch
         - c4.xlarge.elasticsearch
         - c4.2xlarge.elasticsearch
         - c4.4xlarge.elasticsearch
         - c4.8xlarge.elasticsearch
         - i2.xlarge.elasticsearch
         - i2.2xlarge.elasticsearch
         - i3.large.elasticsearch
         - i3.xlarge.elasticsearch
         - i3.2xlarge.elasticsearch
         - i3.4xlarge.elasticsearch
         - i3.8xlarge.elasticsearch
         - i3.16xlarge.elasticsearch
         - m4.large.elasticsearch
         - m4.xlarge.elasticsearch
         - m4.2xlarge.elasticsearch
         - m4.4xlarge.elasticsearch
         - m4.8xlarge.elasticsearch
         - r3.large.elasticsearch
         - r3.xlarge.elasticsearch
         - r3.2xlarge.elasticsearch
         - r3.4xlarge.elasticsearch
         - r3.8xlarge.elasticsearch
         - t2.small.elasticsearch
         - t2.medium.elasticsearch
         - t3.small.elasticsearch
         - t3.medium.elasticsearch
      DedicatedMasterCount:
        Description: No of master nodes.
        Type: 'String'
        Default: 3
        AllowedValues: ['3','4','5']
      AvailabilityZone1:
        Description: List of availability zones in which subnets would be get created
        Type: AWS::EC2::AvailabilityZone::Name
      AvailabilityZone2:
        Description: List of availability zones in which subnets would be get created
        Type: AWS::EC2::AvailabilityZone::Name
      VpcCidr:
        Description: cidr Block for the VPC
        Type: String
        Default: 10.0.0.0/16
        AllowedPattern: "[a-zA-Z0-9]+\\..+"
      SubnetCidr1:
        Description: cidr Block for the Subnet1
        Type: String
        Default: 10.0.0.0/24
        AllowedPattern: "[a-zA-Z0-9]+\\..+"
      SubnetCidr2:
        Description: cidr Block for the Subnet2
        Type: String
        Default: 10.0.1.0/24
        AllowedPattern: "[a-zA-Z0-9]+\\..+"
   
   
    Resources:
      ELasticSearch:
        Type: 'AWS::Elasticsearch::Domain'
        Properties:
          ElasticsearchClusterConfig:
            DedicatedMasterEnabled: true
            InstanceCount: !Ref InstanceCount
            ZoneAwarenessEnabled: true
            InstanceType: !Ref InstanceType
            DedicatedMasterType: !Ref DedicatedMasterType
            DedicatedMasterCount: !Ref DedicatedMasterCount
          DomainName: !Ref DomainName
          ElasticsearchVersion: !Ref ElasticsearchVersion
          AccessPolicies:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Principal:
                AWS: '*'
              Action:
              - 'es:*'
              Resource: '*'
          VPCOptions:
            SecurityGroupIds:
            - !GetAtt ELKServerSecurityGroup.GroupId
            SubnetIds: 
            - !Ref Subnet1
            - !Ref Subnet2
          EBSOptions: 
            EBSEnabled: !Ref EBSEnabled
            VolumeSize: !Ref EBSVolumeSize
            VolumeType: standard
          Tags: 
           - Key: 'Environment'
             Value: !Ref Environment 
           - Key: Name
             Value: !Ref AWS::StackName
           
      VPC:
        Type: 'AWS::EC2::VPC'
        Properties:
          CidrBlock: !Ref VpcCidr
          Tags: 
           - Key: 'Environment'
             Value: !Ref Environment 
           - Key: Name
             Value: !Ref AWS::StackName       
         
      Subnet1:
        Type: 'AWS::EC2::Subnet'
        Properties:  
          VpcId: !Ref VPC
          CidrBlock: !Ref SubnetCidr1
          AvailabilityZone: !Ref AvailabilityZone1
          Tags:
           - Key: 'Environment'
             Value: !Ref Environment
           - Key: Name
             Value: !Ref AWS::StackName               
             
      Subnet2:
        Type: 'AWS::EC2::Subnet'
        Properties:  
          VpcId: !Ref VPC
          CidrBlock: !Ref SubnetCidr1
          AvailabilityZone: !Ref AvailabilityZone2  
          Tags:
           - Key: 'Environment'
             Value: !Ref Environment
           - Key: Name
             Value: !Ref AWS::StackName               
             
      myInternetGateway:
        Type: AWS::EC2::InternetGateway
        Properties:
          Tags:
           - Key: 'Environment'
             Value: !Ref Environment
           - Key: Name
             Value: !Ref AWS::StackName               
             
      GatewayToInternet:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
          VpcId: !Ref VPC 
          InternetGatewayId: !Ref myInternetGateway
          
      myRouteTable:
       Type: AWS::EC2::RouteTable
       Properties:
         VpcId: !Ref VPC
         Tags:
          - Key: 'Environment'
            Value: !Ref Environment
          - Key: Name
            Value: !Ref AWS::StackName 
         
      myRoute:
       Type: AWS::EC2::Route
       DependsOn: GatewayToInternet
       Properties:
         RouteTableId: !Ref myRouteTable
         DestinationCidrBlock: 0.0.0.0/0
         GatewayId: !Ref myInternetGateway
         
      mySubnetRouteTableAssociation1:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
          SubnetId: !Ref Subnet1 
          RouteTableId: !Ref myRouteTable
          
      mySubnetRouteTableAssociation2:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
          SubnetId: !Ref Subnet2 
          RouteTableId: !Ref myRouteTable         
        
      ELKServerSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
          GroupDescription: allow connections from specified CIDR ranges
          SecurityGroupIngress:
           - IpProtocol: tcp
             FromPort: 0
             ToPort: 65535
             CidrIp: 0.0.0.0/0
          VpcId: !Ref VPC
             
    Outputs:
      SecurityGroupId:
        Description: The security group used to manage access to Elasticsearch.
        Value: !GetAtt ELKServerSecurityGroup.GroupId
      DomainArn:
        Description: The Amazon Resource Name (ARN) of the domain
        Value: !GetAtt ELasticSearch.DomainArn
      DomainEndpoint:
        Description: The domain-specific endpoint that's used for requests to the Elasticsearch APIs
        Value: !GetAtt ELasticSearch.DomainEndpoint
      
      
      
           
          
       